name: actual-budget

services:
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    external: true