  name: mealie

  services:
    mealie:
      image: ghcr.io/mealie-recipes/mealie:latest
      container_name: mealie
      restart: unless-stopped
      volumes:
        - ./data:/app/data
      environment:
        ALLOW_SIGNUP: "false"
        LOG_LEVEL: "INFO"
        DB_ENGINE: sqlite
      networks:
        - app-network
  networks:
    app-network:
      external: true
